name: Build Unity Android APK

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  buildAndroid:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}

      - name: Activate Unity
        uses: game-ci/unity-activate@v2
        with:
          unityVersion: 2022.3.60f1c1
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          
      - name: Build Android
        uses: game-ci/unity-builder@v3
        with:
          unityVersion: 2022.3.60f1c1      
          targetPlatform: Android
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

      - uses: actions/upload-artifact@v4
        with:
          name: AndroidBuild
          path: build/Android/*.apk
